# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180304_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_birthday',
            new_name='date_of_birth',
        ),
    ]
